// -----------------------------------------------------------------------------
// File: cpp\tests\test_core.cpp
// Purpose: Unit tests for the native core: JSON writer/parser, .NET time
//          formats, model serialization order/defaults, envelope handling,
//          and (when present) golden files generated by the .NET build.
// -----------------------------------------------------------------------------

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include "../src/version.h"
#include "../src/core/ipc.h"
#include "../src/core/pipe.h"
#include "../src/ui/update_service.h"

namespace {

int g_failures = 0;
int g_checks = 0;

void check(bool condition, const std::string& label) {
    ++g_checks;
    if (!condition) {
        ++g_failures;
        std::printf("FAIL: %s\n", label.c_str());
    }
}

void check_equal(const std::string& actual, const std::string& expected, const std::string& label) {
    ++g_checks;
    if (actual != expected) {
        ++g_failures;
        std::printf("FAIL: %s\n  expected: %s\n  actual:   %s\n",
                    label.c_str(), expected.c_str(), actual.c_str());
    }
}

// ---------------------------------------------------------------------------

void test_app_version() {
    std::string numeric =
        std::to_string(XACTCOPY_VERSION_MAJOR) + "." +
        std::to_string(XACTCOPY_VERSION_MINOR) + "." +
        std::to_string(XACTCOPY_VERSION_BUILD) + "." +
        std::to_string(XACTCOPY_VERSION_REVISION);
    check_equal(XACTCOPY_VERSION_STRING, numeric,
                "Product version string matches numeric version");

    xact::ui::AppVersion published =
        xact::ui::update_detail::parse_version("v" XACTCOPY_VERSION_STRING);
    check(!xact::ui::UpdateService::is_update_available(
              xact::ui::kNativeVersion, published),
          "Current published version is not reported as an update");

    ++published.revision;
    check(xact::ui::UpdateService::is_update_available(
              xact::ui::kNativeVersion, published),
          "Newer revision is reported as an update");
}

void test_timespan_format() {
    using xact::time::TimeSpan;

    check_equal(TimeSpan::zero().to_string(), "00:00:00", "TimeSpan zero");
    check_equal(TimeSpan::from_seconds(10).to_string(), "00:00:10", "TimeSpan 10s");
    check_equal(TimeSpan::from_seconds(8).to_string(), "00:00:08", "TimeSpan 8s");
    check_equal(TimeSpan::from_milliseconds(500).to_string(), "00:00:00.5000000", "TimeSpan 500ms");
    check_equal(TimeSpan::from_milliseconds(250).to_string(), "00:00:00.2500000", "TimeSpan 250ms");
    check_equal(TimeSpan::from_minutes(90).to_string(), "01:30:00", "TimeSpan 90min");
    check_equal(TimeSpan(-TimeSpan::from_seconds(5).ticks).to_string(), "-00:00:05", "TimeSpan negative");

    // 1 day, 2 h, 3 min, 4.567 s
    TimeSpan big(1 * xact::time::TicksPerDay + 2 * xact::time::TicksPerHour +
                 3 * xact::time::TicksPerMinute + 4 * xact::time::TicksPerSecond + 5'670'000);
    check_equal(big.to_string(), "1.02:03:04.5670000", "TimeSpan d.hh:mm:ss.fffffff");

    auto parsed = TimeSpan::parse("1.02:03:04.5670000");
    check(parsed.has_value() && parsed->ticks == big.ticks, "TimeSpan parse round-trip");
    parsed = TimeSpan::parse("00:00:00.5000000");
    check(parsed.has_value() && parsed->ticks == TimeSpan::from_milliseconds(500).ticks, "TimeSpan parse 500ms");
    parsed = TimeSpan::parse("-00:00:05");
    check(parsed.has_value() && parsed->ticks == -TimeSpan::from_seconds(5).ticks, "TimeSpan parse negative");
    parsed = TimeSpan::parse("00:00:10");
    check(parsed.has_value() && parsed->ticks == TimeSpan::from_seconds(10).ticks, "TimeSpan parse 10s");
    parsed = TimeSpan::parse("10:30");
    check(parsed.has_value() && parsed->ticks == TimeSpan::from_minutes(630).ticks, "TimeSpan parse hh:mm");
    check(!TimeSpan::parse("garbage").has_value(), "TimeSpan parse rejects garbage");
    check(!TimeSpan::parse("00:75:00").has_value(), "TimeSpan parse rejects minutes>59");
}

void test_datetimeoffset_format() {
    using xact::time::DateTimeOffset;

    check_equal(DateTimeOffset::min_value().to_string(), "0001-01-01T00:00:00+00:00", "DTO min value");

    // 2026-07-23T01:02:03.0040005 UTC
    auto parsed = DateTimeOffset::parse("2026-07-23T01:02:03.0040005+00:00");
    check(parsed.has_value(), "DTO parse basic");
    if (parsed.has_value()) {
        check_equal(parsed->to_string(), "2026-07-23T01:02:03.0040005+00:00", "DTO round-trip");
    }

    // Trailing-zero trimming: .5000000 -> .5
    auto half = DateTimeOffset::parse("2026-01-02T03:04:05.5000000+00:00");
    check(half.has_value(), "DTO parse .5000000");
    if (half.has_value()) {
        check_equal(half->to_string(), "2026-01-02T03:04:05.5+00:00", "DTO trims trailing zeros");
    }

    // Zero fraction omitted entirely.
    auto whole = DateTimeOffset::parse("2026-01-02T03:04:05+00:00");
    check(whole.has_value(), "DTO parse without fraction");
    if (whole.has_value()) {
        check_equal(whole->to_string(), "2026-01-02T03:04:05+00:00", "DTO omits zero fraction");
    }

    // 'Z' accepted on read, preserved as +00:00 on write.
    auto zulu = DateTimeOffset::parse("2026-01-02T03:04:05Z");
    check(zulu.has_value(), "DTO parse Z");
    if (zulu.has_value() && whole.has_value()) {
        check(zulu->utc_ticks() == whole->utc_ticks(), "DTO Z == +00:00 instant");
    }

    // Non-UTC offsets round-trip and compare by instant.
    auto offset = DateTimeOffset::parse("2026-01-02T08:34:05.25+05:30");
    check(offset.has_value(), "DTO parse +05:30");
    if (offset.has_value()) {
        check_equal(offset->to_string(), "2026-01-02T08:34:05.25+05:30", "DTO offset round-trip");
        auto utc = DateTimeOffset::parse("2026-01-02T03:04:05.25+00:00");
        check(utc.has_value() && *offset == *utc, "DTO instant equality across offsets");
    }

    auto negative = DateTimeOffset::parse("2026-01-01T20:04:05-07:00");
    check(negative.has_value(), "DTO parse -07:00");
    if (negative.has_value()) {
        check_equal(negative->to_string(), "2026-01-01T20:04:05-07:00", "DTO negative offset round-trip");
    }

    // Leap-year and calendar sanity.
    auto leap = DateTimeOffset::parse("2024-02-29T12:00:00+00:00");
    check(leap.has_value(), "DTO parse leap day");
    if (leap.has_value()) {
        check_equal(leap->to_string(), "2024-02-29T12:00:00+00:00", "DTO leap day round-trip");
    }

    // now_utc produces offset 0 and a plausible year.
    auto now = DateTimeOffset::now_utc();
    check(now.offset_minutes == 0, "DTO now offset 0");
    std::string now_text = now.to_string();
    check(now_text.size() >= 25 && now_text.substr(0, 2) == "20", "DTO now format sane: " + now_text);
}

void test_json_writer_and_parser() {
    using namespace xact::json;

    // Compact output and STJ-compatible escaping.
    Writer w;
    w.begin_object();
    w.key("A"); w.value("plain");
    w.key("B"); w.value("quote\" backslash\\ <tag> & 'x' +1 `t");
    w.key("C"); w.value("newline\ntab\tcr\r");
    w.key("D"); w.value("\x01");
    w.key("E"); w.value("café \xE2\x82\xAC \xF0\x9F\x98\x80"); // é, €, 😀
    w.key("F"); w.value(static_cast<std::int64_t>(-42));
    w.key("G"); w.value(true);
    w.key("H"); w.value(nullptr);
    w.key("I"); w.begin_array(); w.value(1); w.value(2); w.end_array();
    w.end_object();
    std::string out = w.take();

    check_equal(out,
        "{\"A\":\"plain\","
        "\"B\":\"quote\\u0022 backslash\\\\ \\u003Ctag\\u003E \\u0026 \\u0027x\\u0027 \\u002B1 \\u0060t\","
        "\"C\":\"newline\\ntab\\tcr\\r\","
        "\"D\":\"\\u0001\","
        "\"E\":\"caf\\u00E9 \\u20AC \\uD83D\\uDE00\","
        "\"F\":-42,\"G\":true,\"H\":null,\"I\":[1,2]}",
        "Writer STJ-compatible output");

    // Parser round-trips the writer's output.
    Value root = parse(out);
    const Object* obj = root.as_object();
    check(obj != nullptr, "Parser returns object");
    if (obj != nullptr) {
        check_equal(obj->find("B")->as_string(), "quote\" backslash\\ <tag> & 'x' +1 `t", "Parser unescapes B");
        check_equal(obj->find("E")->as_string(), "café \xE2\x82\xAC \xF0\x9F\x98\x80", "Parser unescapes unicode");
        check(obj->find("F")->as_int64() == -42, "Parser int");
        check(obj->find("g") != nullptr && obj->find("g")->as_bool(), "Parser case-insensitive lookup");
        check(obj->find("H")->is_null(), "Parser null");
        check(obj->find("I")->as_array()->size() == 2, "Parser array");
    }

    // Doubles.
    Writer wd;
    wd.begin_object();
    wd.key("Zero"); wd.value(0.0);
    wd.key("Half"); wd.value(0.5);
    wd.key("Big"); wd.value(123456.789);
    wd.end_object();
    check_equal(wd.take(), "{\"Zero\":0,\"Half\":0.5,\"Big\":123456.789}", "Writer double formats");

    Value num = parse("{\"A\":1.5e3,\"B\":-0.25,\"C\":9223372036854775807}");
    check(num.as_object()->find("A")->as_double() == 1500.0, "Parser scientific double");
    check(num.as_object()->find("B")->as_double() == -0.25, "Parser negative double");
    check(num.as_object()->find("C")->as_int64() == 9223372036854775807LL, "Parser int64 max");

    // Whitespace tolerance and malformed input.
    Value ws = parse("  { \"A\" : [ 1 , 2 ] , \"B\" : \"x\" }  ");
    check(ws.as_object() != nullptr && ws.as_object()->find("A")->as_array()->size() == 2, "Parser whitespace");
    bool threw = false;
    try { parse("{\"A\":}"); } catch (const ParseError&) { threw = true; }
    check(threw, "Parser rejects malformed value");
    threw = false;
    try { parse("{\"A\":1} trailing"); } catch (const ParseError&) { threw = true; }
    check(threw, "Parser rejects trailing garbage");

    // Surrogate-pair escape parsing.
    Value emoji = parse("{\"E\":\"\\uD83D\\uDE00\"}");
    check_equal(emoji.as_object()->find("E")->as_string(), "\xF0\x9F\x98\x80", "Parser surrogate pair");
}

void test_options_roundtrip() {
    using namespace xact;

    models::CopyJobOptions options;
    options.SourceRoot = "D:\\Source";
    options.DestinationRoot = "E:\\Dest";
    options.OperationMode = models::JobOperationMode::ScanOnly;
    options.SelectedRelativePaths = {"a.txt", "sub\\b.bin"};
    options.MaxRetries = 7;
    options.OperationTimeout = time::TimeSpan::from_seconds(30);
    options.VerificationModeValue = models::VerificationMode::Full;
    options.WorkerTelemetryProfileValue = models::WorkerTelemetryProfile::Debug;

    json::Writer w;
    options.to_json(w);
    std::string serialized = w.take();

    models::CopyJobOptions restored = models::CopyJobOptions::from_json(json::parse(serialized));
    check(restored.OperationMode == models::JobOperationMode::ScanOnly, "Options mode round-trip");
    check_equal(restored.SourceRoot, "D:\\Source", "Options source round-trip");
    check(restored.SelectedRelativePaths.size() == 2 &&
          restored.SelectedRelativePaths[1] == "sub\\b.bin", "Options list round-trip");
    check(restored.MaxRetries == 7, "Options retries round-trip");
    check(restored.OperationTimeout == time::TimeSpan::from_seconds(30), "Options timespan round-trip");
    check(restored.VerificationModeValue == models::VerificationMode::Full, "Options enum round-trip");
    check(restored.WorkerTelemetryProfileValue == models::WorkerTelemetryProfile::Debug, "Options telemetry round-trip");
    check(restored.LockContentionProbeInterval == time::TimeSpan::from_milliseconds(500), "Options default timespan kept");
    check(restored.RescueScrapeRetries == 2, "Options default int kept");

    // Missing fields keep defaults; unknown fields are ignored; enums parse
    // case-insensitively and from integers.
    auto partial = models::CopyJobOptions::from_json(json::parse(
        "{\"sourceroot\":\"X:\\\\\",\"OverwritePolicy\":\"skipexisting\",\"SymlinkHandling\":1,"
        "\"NotARealField\":123}"));
    check_equal(partial.SourceRoot, "X:\\", "Options case-insensitive field");
    check(partial.OverwritePolicyValue == models::OverwritePolicy::SkipExisting, "Options case-insensitive enum");
    check(partial.SymlinkHandling == models::SymlinkHandlingMode::Follow, "Options numeric enum");
    check(partial.MaxRetries == 12, "Options missing field default");
}

void test_envelope() {
    using namespace xact;

    ipc::WorkerLogEvent log_event;
    log_event.JobId = "job-1";
    log_event.Message = "hello <world>";
    log_event.TimestampUtc = *time::DateTimeOffset::parse("2026-07-23T01:02:03.0040005+00:00");

    std::string envelope = ipc::serialize_envelope_for(
        ipc::message_types::WorkerLogEvent, log_event, "corr-9",
        time::DateTimeOffset::parse("2026-07-23T01:02:03+00:00"));

    check_equal(envelope,
        "{\"ProtocolVersion\":1,\"MessageType\":\"WorkerLogEvent\",\"CorrelationId\":\"corr-9\","
        "\"SentUtc\":\"2026-07-23T01:02:03+00:00\",\"Payload\":{\"JobId\":\"job-1\","
        "\"Message\":\"hello \\u003Cworld\\u003E\",\"TimestampUtc\":\"2026-07-23T01:02:03.0040005+00:00\"}}",
        "Envelope byte layout");

    std::string message_type;
    check(ipc::try_read_message_type(envelope, message_type), "try_read_message_type accepts");
    check_equal(message_type, "WorkerLogEvent", "try_read_message_type value");

    check(!ipc::try_read_message_type("{\"ProtocolVersion\":2,\"MessageType\":\"X\"}", message_type),
          "try_read_message_type rejects wrong version");
    check(!ipc::try_read_message_type("not json at all", message_type),
          "try_read_message_type rejects garbage");

    auto [header, payload] = ipc::parse_envelope(envelope);
    check(header.protocol_version == 1, "Envelope version");
    check_equal(header.message_type, "WorkerLogEvent", "Envelope type");
    check_equal(header.correlation_id, "corr-9", "Envelope correlation");
    auto restored = ipc::WorkerLogEvent::from_json(payload);
    check_equal(restored.Message, "hello <world>", "Envelope payload round-trip");
    check(restored.TimestampUtc == log_event.TimestampUtc, "Envelope timestamp round-trip");

    bool threw = false;
    try {
        ipc::parse_envelope("{\"ProtocolVersion\":99,\"MessageType\":\"X\",\"Payload\":{}}");
    } catch (const std::exception&) {
        threw = true;
    }
    check(threw, "Envelope rejects wrong protocol version");
}

void test_frame_layer() {
    using namespace xact;

    // In-process loopback over a private named pipe exercises framing without
    // a child process.
    std::wstring name = L"xactcopy-selftest-" + std::to_wstring(GetCurrentProcessId()) +
                        L"-" + std::to_wstring(GetTickCount64());
    pipe::MessagePipe server = pipe::MessagePipe::create_server(name);
    pipe::CancellationEvent cancel;

    std::string received_small, received_large, received_empty;
    bool clean_eof = false;

    std::thread server_thread([&] {
        server.wait_for_connection(cancel);
        received_small = server.read_message(cancel).value_or("<none>");
        received_large = server.read_message(cancel).value_or("<none>");
        received_empty = server.read_message(cancel).value_or("<none>");
        clean_eof = !server.read_message(cancel).has_value();
    });

    pipe::MessagePipe client = pipe::MessagePipe::connect_client(name, 5000);
    client.write_message("hello frame", cancel);
    std::string large(1'000'000, 'x');
    large[12345] = '\xC3'; large[12346] = '\xA9'; // embed multi-byte UTF-8
    client.write_message(large, cancel);
    client.write_message("", cancel);
    client.close();

    server_thread.join();
    check_equal(received_small, "hello frame", "Frame small message");
    check(received_large == large, "Frame 1MB message");
    check(received_empty.empty(), "Frame empty message");
    check(clean_eof, "Frame clean EOF at boundary");

    bool threw = false;
    pipe::MessagePipe dummy;
    try {
        std::string oversized(static_cast<std::size_t>(pipe::MaximumPayloadBytes) + 1, 'y');
        dummy.write_message(oversized, cancel);
    } catch (const std::length_error&) {
        threw = true;
    }
    check(threw, "Frame rejects oversized payload");
}

// ---------------------------------------------------------------------------
// Golden files. These were originally emitted by the real .NET serializer and
// are now frozen fixtures in tests/golden: they pin the wire format the shipped
// protocol and stored artifacts use. Skipped silently when not present.
// ---------------------------------------------------------------------------

std::string read_file(const std::string& path) {
    std::ifstream stream(path, std::ios::binary);
    if (!stream) return std::string();
    std::ostringstream buffer;
    buffer << stream.rdbuf();
    return buffer.str();
}

void test_goldens(const std::string& golden_dir) {
    using namespace xact;

    std::string escapes = read_file(golden_dir + "/string_escapes.json");
    if (escapes.empty()) {
        std::printf("NOTE: goldens not found in %s; pass the goldens directory.\n", golden_dir.c_str());
        return;
    }

    // string_escapes.json: JSON array where entry N is STJ's serialization of
    // a known input; we regenerate each input and byte-compare our writer.
    {
        json::Value parsed = json::parse(escapes);
        const json::Array* arr = parsed.as_array();
        check(arr != nullptr && !arr->empty(), "Golden escapes array present");
        if (arr != nullptr) {
            for (std::size_t i = 0; i < arr->size(); ++i) {
                const std::string& raw = (*arr)[i].as_string();
                json::Writer w;
                w.value(raw);
                // Golden entries are the raw strings; serialize both sides and
                // compare against STJ's bytes extracted from the file itself.
                (void)w;
                (void)raw;
            }
            // Byte comparison happens on the whole-array level: re-serialize
            // every parsed string with our writer and match the .NET file.
            json::Writer all;
            all.begin_array();
            for (const auto& item : *arr) all.value(item.as_string());
            all.end_array();
            check_equal(all.take(), escapes, "Golden escapes byte-for-byte");
        }
    }

    std::string options_golden = read_file(golden_dir + "/options_default.json");
    if (!options_golden.empty()) {
        models::CopyJobOptions defaults;
        json::Writer w;
        defaults.to_json(w);
        check_equal(w.take(), options_golden, "Golden default CopyJobOptions byte-for-byte");
    }

    std::string envelope_golden = read_file(golden_dir + "/envelope_log.json");
    if (!envelope_golden.empty()) {
        auto [header, payload] = ipc::parse_envelope(envelope_golden);
        check_equal(header.message_type, "WorkerLogEvent", "Golden envelope type");
        auto log_event = ipc::WorkerLogEvent::from_json(payload);
        std::string regenerated = ipc::serialize_envelope_for(
            ipc::message_types::WorkerLogEvent, log_event, header.correlation_id, header.sent_utc);
        check_equal(regenerated, envelope_golden, "Golden envelope byte-for-byte");
    }

    std::string result_golden = read_file(golden_dir + "/envelope_result.json");
    if (!result_golden.empty()) {
        auto [header, payload] = ipc::parse_envelope(result_golden);
        auto result_event = ipc::WorkerJobResultEvent::from_json(payload);
        std::string regenerated = ipc::serialize_envelope_for(
            ipc::message_types::WorkerJobResultEvent, result_event, header.correlation_id, header.sent_utc);
        check_equal(regenerated, result_golden, "Golden result envelope byte-for-byte");
    }

    std::string start_golden = read_file(golden_dir + "/envelope_start.json");
    if (!start_golden.empty()) {
        auto [header, payload] = ipc::parse_envelope(start_golden);
        auto command = ipc::StartJobCommand::from_json(payload);
        std::string regenerated = ipc::serialize_envelope_for(
            ipc::message_types::StartJobCommand, command, header.correlation_id, header.sent_utc);
        check_equal(regenerated, start_golden, "Golden StartJob envelope byte-for-byte");
    }

    std::string progress_golden = read_file(golden_dir + "/envelope_progress.json");
    if (!progress_golden.empty()) {
        auto [header, payload] = ipc::parse_envelope(progress_golden);
        auto progress_event = ipc::WorkerProgressEvent::from_json(payload);
        std::string regenerated = ipc::serialize_envelope_for(
            ipc::message_types::WorkerProgressEvent, progress_event, header.correlation_id, header.sent_utc);
        check_equal(regenerated, progress_golden, "Golden progress envelope byte-for-byte");
    }

    std::string heartbeat_golden = read_file(golden_dir + "/envelope_heartbeat.json");
    if (!heartbeat_golden.empty()) {
        auto [header, payload] = ipc::parse_envelope(heartbeat_golden);
        auto heartbeat = ipc::WorkerHeartbeatEvent::from_json(payload);
        std::string regenerated = ipc::serialize_envelope_for(
            ipc::message_types::WorkerHeartbeatEvent, heartbeat, header.correlation_id, header.sent_utc);
        check_equal(regenerated, heartbeat_golden, "Golden heartbeat envelope byte-for-byte");
    }
}

} // namespace

int main(int argc, char** argv) {
    test_app_version();
    test_timespan_format();
    test_datetimeoffset_format();
    test_json_writer_and_parser();
    test_options_roundtrip();
    test_envelope();
    test_frame_layer();

    std::string golden_dir = argc > 1 ? argv[1] : "tests/golden";
    test_goldens(golden_dir);

    if (g_failures == 0) {
        std::printf("PASS: %d checks\n", g_checks);
        return 0;
    }
    std::printf("FAILED: %d of %d checks\n", g_failures, g_checks);
    return 1;
}
